repos:
  - name: spark
    github_repo: dbanda/charts
    branch: master
    charts_path:
      - stable/spark
  - name: azure-industrial-iot
    github_repo: Azure/Industrial-IoT
    branch: master
    charts_path:
      - deploy/helm/azure-industrial-iot
